target_columns = [
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.1. Pan, tortillas y cereales, 01 Tortillas y derivados del maíz, 014 Tortilla de maíz",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.1. Pan, tortillas y cereales, 02 Pan, 008 Pan blanco",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.1. Pan, tortillas y cereales, 02 Pan, 010 Pan dulce",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.2. Carnes, 05 Carne de ave, 022 Pollo",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.2. Carnes, 07 Carne y vísceras de res, 018 Carne de res",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.2. Carnes, 07 Carne y vísceras de res, 025 Vísceras de res",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.2. Carnes, 08 Carnes frías, secas y embutidos, 020 Chorizo",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.2. Carnes, 08 Carnes frías, secas y embutidos, 021 Jamón",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.2. Carnes, 08 Carnes frías, secas y embutidos, 023 Salchichas",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.2. Carnes, 08 Carnes frías, secas y embutidos, 024 Tocino",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 11 Leche pasteurizada y fresca, 034 Leche pasteurizada y fresca",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 12 Leche procesada, 032 Leche en polvo",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 12 Leche procesada, 033 Leche evaporada y condensada",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 13 Derivados de leche, 030 Crema y otros productos a base de leche",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 13 Derivados de leche, 036 Queso amarillo",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 13 Derivados de leche, 037 Queso fresco",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 13 Derivados de leche, 038 Queso manchego y Chihuahua",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 13 Derivados de leche, 039 Queso Oaxaca y asadero",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 13 Derivados de leche, 044 Mantequilla",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.4. Leche, derivados de leche y huevo, 14 Huevo, 031 Huevo",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 045 Aguacate",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 047 Guayaba",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 048 Limón",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 049 Manzana",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 050 Melón",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 051 Naranja",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 052 Papaya",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 054 Piña",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 055 Plátanos",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 056 Sandía",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 16 Frutas frescas, 057 Uva",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 060 Calabacita",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 061 Cebolla",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 062 Chayote",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 063 Chile poblano",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 065 Chile serrano",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 067 Ejotes",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 070 Jitomate",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 071 Lechuga y col",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 072 Nopales",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 073 Papa y otros tubérculos",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 075 Pepino",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 076 Tomate verde",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 17 Hortalizas frescas, 078 Zanahoria",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 18 Legumbres secas, 068 Frijol",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.6. Frutas y hortalizas, 19 Frutas y legumbres procesadas, 095 Jugos o néctares envasados",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.7. Azúcar, café y refrescos envasados, 22 Refrescos envasados y agua embotellada, 099 Agua embotellada",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 1. Alimentos, bebidas y tabaco, 1.1. Alimentos, 1.1.7. Azúcar, café y refrescos envasados, 22 Refrescos envasados y agua embotellada, 100 Refrescos envasados",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 5. Salud y cuidado personal, 5.1. Salud, 5.1.1. Medicamentos y aparatos, 55 Medicamentos, 184 Analgésicos",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 5. Salud y cuidado personal, 5.1. Salud, 5.1.1. Medicamentos y aparatos, 55 Medicamentos, 185 Antibióticos",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 5. Salud y cuidado personal, 5.1. Salud, 5.1.1. Medicamentos y aparatos, 55 Medicamentos, 186 Antigripales",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 5. Salud y cuidado personal, 5.1. Salud, 5.1.1. Medicamentos y aparatos, 55 Medicamentos, 188 Cardiovasculares",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 5. Salud y cuidado personal, 5.1. Salud, 5.1.1. Medicamentos y aparatos, 55 Medicamentos, 189 Dermatológicos",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 5. Salud y cuidado personal, 5.1. Salud, 5.1.1. Medicamentos y aparatos, 55 Medicamentos, 190 Expectorantes y descongestivos",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 6. Transporte, 6.1. Transporte público, 6.1.2. Transporte público foráneo, 62 Transporte público foráneo, 222 Autobús foráneo",
    "Índice Nacional de Precios al Consumidor. Base segunda quincena Julio 2018. Actualización de Canasta y Ponderadores 2024 (mensual), Por ciudad, 7. Area Metropolitana de la Cd. de México, Índice de precios al consumidor, por objeto del gasto, Índice general, 6. Transporte, 6.1. Transporte público, 6.1.2. Transporte público foráneo, 62 Transporte público foráneo, 227 Transporte aéreo",
]

mapping_productos_inpc = {
    "Tortilla de maíz": "014 Tortilla de maíz",
    "Pan blanco": "008 Pan blanco",
    "Pan dulce": "010 Pan dulce",
    "Pollo": "022 Pollo",
    "Carne de res": "018 Carne de res",
    "Vísceras de res": "025 Vísceras de res",
    "Chorizo": "020 Chorizo",
    "Jamón": "021 Jamón",
    "Salchichas": "023 Salchichas",
    "Tocino": "024 Tocino",
    "Leche pasteurizada": "034 Leche pasteurizada y fresca",
    "Leche en polvo": "032 Leche en polvo",
    "Leche evaporada": "033 Leche evaporada y condensada",
    "Crema de leche": "030 Crema y otros productos a base de leche",
    "Queso amarillo": "036 Queso amarillo",
    "Queso fresco": "037 Queso fresco",
    "Queso manchego o Chihuahua": "038 Queso manchego y Chihuahua",
    "Queso Oaxaca o asadero": "039 Queso Oaxaca y asadero",
    "Mantequilla": "044 Mantequilla",
    "Huevo": "031 Huevo",
    "Aguacate": "045 Aguacate",
    "Guayaba": "047 Guayaba",
    "Limón": "048 Limón",
    "Manzana": "049 Manzana",
    "Melón": "050 Melón",
    "Naranja": "051 Naranja",
    "Papaya": "052 Papaya",
    "Piña": "054 Piña",
    "Plátanos": "055 Plátanos",
    "Sandía": "056 Sandía",
    "Uva": "057 Uva",
    "Calabacita": "060 Calabacita",
    "Cebolla": "061 Cebolla",
    "Chayote": "062 Chayote",
    "Chile poblano": "063 Chile poblano",
    "Chile serrano": "065 Chile serrano",
    "Ejotes": "067 Ejotes",
    "Jitomate": "070 Jitomate",
    "Lechuga y col": "071 Lechuga y col",
    "Nopales": "072 Nopales",
    "Papa y otros tubérculos": "073 Papa y otros tubérculos",
    "Pepino": "075 Pepino",
    "Tomate verde": "076 Tomate verde",
    "Zanahoria": "078 Zanahoria",
    "Frijol": "068 Frijol",
    "Jugos o néctares envasados": "095 Jugos o néctares envasados",
    "Agua embotellada": "099 Agua embotellada",
    "Refrescos envasados": "100 Refrescos envasados",
    "Analgésicos": "184 Analgésicos",
    "Antibióticos": "185 Antibióticos",
    "Antigripales": "186 Antigripales",
    "Cardiovasculares": "188 Cardiovasculares",
    "Dermatológicos": "189 Dermatológicos",
    "Expectorantes y descongestivos": "190 Expectorantes y descongestivos",
    "Autobús foráneo": "222 Autobús foráneo",
    "Transporte aéreo": "227 Transporte aéreo",
}

mapping_ciudades_inpc = {
    "Acapulco, Gro.": "inpc_acapulco",
    "Aguascalientes, Ags.": "inpc_aguascalientes",
    #'Atlacomulco, Méx.': 'inpc_atlacomulco', # no está en precios promedios
    "Campeche, Camp.": "inpc_campeche",
    # 'Cancún, Q.R.': 'inpc_cancun', # no está en precios promedios
    "Área Metropolitana de la Cd. de México": "inpc_cdmx",
    "Cd. Acuña, Coah.": "inpc_cd_acuna",
    "Jiménez, Chih.": "inpc_cd_jimenez",
    "Cd. Juárez, Chih.": "inpc_cd_juarez",
    "Chetumal, Q.R.": "inpc_chetumal",
    "Chihuahua, Chih.": "inpc_chihuahua",
    # 'Coatzacoalcos, Ver.': 'inpc_coatzacoalcos', # no está en precios promedios
    "Colima, Col.": "inpc_colima",
    "Córdoba, Ver.": "inpc_cordoba",
    "Cortazar, Gto.": "inpc_cortazar",
    "Cuernavaca, Mor.": "inpc_cuernavaca",
    "Culiacán, Sin.": "inpc_culiacan",
    "Durango, Dgo.": "inpc_durango",
    # 'Esperanza, Son.': 'inpc_esperanza', # no está en precios promedios
    "Fresnillo, Zac.": "inpc_fresnillo",
    "Guadalajara, Jal.": "inpc_guadalajara",
    "Hermosillo, Son.": "inpc_hermosillo",
    "Huatabampo, Son.": "inpc_huatabampo",
    "Iguala, Gro.": "inpc_iguala",
    # 'Izúcar de Matamoros, Pue.': 'inpc_izucar_de_matamoros', # no está en precios promedios
    "Jacona, Mich.": "inpc_jacona",
    "La Paz, B.C.S.": "inpc_la_paz",
    "León, Gto.": "inpc_leon",
    "Matamoros, Tamps.": "inpc_matamoros",
    "Mérida, Yuc.": "inpc_merida",
    "Mexicali, B.C.": "inpc_mexicali",
    "Monclova, Coah.": "inpc_monclova",
    "Monterrey, N.L.": "inpc_monterrey",
    "Morelia, Mich.": "inpc_morelia",
    "Oaxaca, Oax.": "inpc_oaxaca",
    # 'Pachuca, Hgo.': 'inpc_pachuca', # no está en precios promedios
    "Puebla, Pue.": "inpc_puebla",
    "Querétaro, Qro.": "inpc_queretaro",
    # 'Saltillo, Coah.': 'inpc_saltillo', # no está en precios promedios
    "San Andrés Tuxtla, Ver.": "inpc_san_andres_tuxtla",
    "San Luis Potosí, S.L.P.": "inpc_san_luis_potosi",
    "Tampico, Tamps.": "inpc_tampico",
    "Tapachula, Chis.": "inpc_tapachula",
    "Tehuantepec, Oax.": "inpc_tehuantepec",
    "Tepatitlán, Jal.": "inpc_tepatitlan",
    "Tepic, Nay.": "inpc_tepic",
    "Tijuana, B.C.": "inpc_tijuana",
    "Tlaxcala, Tlax.": "inpc_tlaxcala",
    "Toluca, Méx.": "inpc_toluca",
    "Torreón, Coah.": "inpc_torreon",
    "Tulancingo, Hgo.": "inpc_tulancingo",
    # 'Tuxtla Gutiérrez, Chis.': 'inpc_tuxtla_gutierrez', # no está en precios promedios
    "Veracruz, Ver.": "inpc_veracruz",
    "Villahermosa, Tab.": "inpc_villahermosa",
    # 'Zacatecas, Zac.': 'inpc_zacatecas' # no está en precios promedios
}
