municipios_objetivo_46 = [
    "acapulco de juarez",
    "aguascalientes",
    "campeche",
    "cuauhtemoc",
    "acuna",
    "jimenez",
    "juarez",
    "othon p. blanco",
    "chihuahua",
    "colima",
    "cordoba",
    "cortazar",
    "cuernavaca",
    "culiacan",
    "durango",
    "fresnillo",
    "guadalajara",
    "hermosillo",
    "huatabampo",
    "iguala de la independencia",
    "jacona",
    "la paz",
    "leon",
    "matamoros",
    "merida",
    "mexicali",
    "monclova",
    "monterrey",
    "morelia",
    "oaxaca de juarez",
    "puebla",
    "queretaro",
    "san andres tuxtla",
    "san luis potosi",
    "tampico",
    "tapachula",
    "santo domingo tehuantepec",
    "tepatitlan de morelos",
    "tepic",
    "tijuana",
    "tlaxcala",
    "toluca",
    "torreon",
    "tulancingo de bravo",
    "veracruz",
    "centro",
]

MAPEO_CIUDAD_REGION = {
    "Noroeste": [
        "Tijuana",
        "Mexicali",
        "La Paz",
        "Culiacán",
        "Hermosillo",
        "Obregón",
        "Huatabampo",
        "Jiménez",
    ],
    "Noreste": [
        "Monterrey",
        "Monclova",
        "Torreón",
        "Tampico",
        "Matamoros",
        "Victoria",
        "Saltillo",
        "Acuña",
    ],
    "Oeste": [
        "Guadalajara",
        "Colima",
        "Morelia",
        "Tepic",
        "Jacona",
        "Cortázar",
        "Tepatitlán",
    ],
    "Este": [
        "Puebla",
        "Veracruz",
        "Xalapa",
        "Tlaxcala",
        "Córdoba",
        "Tuxtla",
        "Orizaba",
        "Izúcar",
    ],
    "Centro Norte": [
        "Aguascalientes",
        "León",
        "San Luis",
        "Querétaro",
        "Zacatecas",
        "Durango",
        "Fresnillo",
    ],
    "Centro Sur": [
        "Ciudad de México",
        "CDMX",
        "Toluca",
        "Cuernavaca",
        "Atlacomulco",
        "Tulancingo",
        "Pachuca",
    ],
    "Suroeste": [
        "Oaxaca",
        "Chilpancingo",
        "Tapachula",
        "Acapulco",
        "Tehuantepec",
        "Iguala",
    ],
    "Sureste": ["Mérida", "Cancún", "Campeche", "Villahermosa", "Chetumal", "Progreso"],
}
